<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/Basicaggre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pivoting

#### Transforming rows into columns to summarize data in a more readable format.


### Key Rules

1. Always use GROUP BY on the row column
2.Use SUM/COUNT/AVG as the aggregate
3.Use ELSE 0 to avoid NULLs
4.Each unique value becomes a new column

## count(distinct)

In [9]:
import pandas as pd
import sqlalchemy as sa
import psycopg2
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

if 'google.colab' in sys.modules:
    !sudo apt-get update -qq > /dev/null 2>&1
    !sudo apt-get install postgresql -qq > /dev/null 2>&1
    !sudo service postgresql start > /dev/null 2>&1
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '5432';" > /dev/null 2>&1
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

%reload_ext sql
%sql postgresql://postgres:5432@localhost:5432/contoso_100k
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = 0
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;

         table_name
0  currencyexchange
1          customer
2              date
3           product
4             sales
5             store

In [6]:
%%sql

SELECT *

FROM sales

LIMIT 10;

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [9]:
# @title Default title text
%%sql


SELECT
         orderdate,
         COUNT(customerkey) AS total_customers
FROM
    sales
GROUP BY
    orderdate
ORDER BY
    orderdate;

       orderdate  total_customers
0     2015-01-01               25
1     2015-01-02                8
2     2015-01-03               21
3     2015-01-05               10
4     2015-01-06               12
...          ...              ...
3289  2024-04-16               32
3290  2024-04-17               61
3291  2024-04-18               57
3292  2024-04-19               50
3293  2024-04-20               97

[3294 rows x 2 columns]

In [10]:
%%sql

SELECT
        orderdate,
        customerkey,
              COUNT(customerkey) AS total_customers
FROM
       sales
GROUP BY
        orderdate,
        customerkey
  ORDER BY
       orderdate

        orderdate  customerkey  total_customers
0      2015-01-01      1008672                6
1      2015-01-01       254117                4
2      2015-01-01      1772036                1
3      2015-01-01      1895118                2
4      2015-01-01       947009                2
...           ...          ...              ...
83094  2024-04-20      1252615                2
83095  2024-04-20       852158                2
83096  2024-04-20       267690                3
83097  2024-04-20       920105                4
83098  2024-04-20       102304                3

[83099 rows x 3 columns]