<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/CLT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

if 'google.colab' in sys.modules:
    !sudo apt-get update -qq > /dev/null 2>&1
    !sudo apt-get install postgresql -qq > /dev/null 2>&1
    !sudo service postgresql start > /dev/null 2>&1
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '5432';" > /dev/null 2>&1
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

%reload_ext sql
%sql postgresql://postgres:5432@localhost:5432/contoso_100k
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = 0
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [4]:
%%sql


SELECT
          customerkey,
          EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
          SUM(quantity * netprice * exchangerate) AS customer_ltv
FROM
        sales
GROUP BY
      customerkey

       customerkey cohort_year  customer_ltv
0          2089398        2018         98.39
1           418360        2018       2602.96
2          1217159        2022       1420.44
3          1572543        2021        880.45
4            37876        2017      10524.50
...            ...         ...           ...
49482       929360        2016        106.60
49483       560047        2020       1569.99
49484      1110282        2023       2384.39
49485      1573639        2016       6973.42
49486      1603477        2021        136.62

[49487 rows x 3 columns]

In [9]:
%%sql

WITH clt AS (
SELECT
          customerkey,
          EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
          SUM(quantity * netprice * exchangerate) AS customer_ltv
FROM
        sales
        GROUP BY
          customerkey
)

SELECT
          *,
          AVG(customer_ltv) OVER (PARTITION BY cohort_year) AS avg_customer_ltv
FROM
        clt
ORDER BY
          cohort_year,
          customer_ltv DESC

       customerkey cohort_year  customer_ltv  avg_customer_ltv
0          2091581        2015      47518.31           5271.59
1          1331400        2015      45030.18           5271.59
2           471940        2015      41766.12           5271.59
3           394503        2015      40973.28           5271.59
4          1305589        2015      40399.28           5271.59
...            ...         ...           ...               ...
49482      1844408        2024          4.43           2037.55
49483      1223228        2024          4.17           2037.55
49484      1037560        2024          4.14           2037.55
49485       559132        2024          4.02           2037.55
49486       392497        2024          3.49           2037.55

[49487 rows x 4 columns]

Warning: total number of rows (49487) exceeds max_rows (20000). Limiting to first (20000) rows.