<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/Data_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install the psycopg2 library to connect to PostgreSQL
%pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 65.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [2]:
import pandas as pd
import sqlalchemy as sa
import psycopg2
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:

# Load SQL extension
%load_ext sql

# Connect to the database
%sql postgresql://postgres:5432@localhost:5432/contoso_100k

# Enable auto pandas conversion
%config SqlMagic.autopandas = True

# Disable named parameters
%config SqlMagic.named_parameters = "disabled"

# Display numbers to 2 decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [11]:
%%sql
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2              date
3           product
4             sales
5             store

In [12]:
%%sql

SELECT table_name
FROM information_schema.tables

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

209 rows affected.

               table_name
0        currencyexchange
1                customer
2                   sales
3                    date
4                 product
..                    ...
204       foreign_servers
205    _pg_foreign_tables
206  user_mapping_options
207        foreign_tables
208     _pg_user_mappings

[209 rows x 1 columns]

In [13]:
%%sql

SELECT *
FROM DATE

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3653 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3648,2024-12-27,20241227,2024,Q4-2024,8100,Q4,December 2024,Dec 2024,24300,December,Dec,12,Friday,Fri,6,1,2507
3649,2024-12-28,20241228,2024,Q4-2024,8100,Q4,December 2024,Dec 2024,24300,December,Dec,12,Saturday,Sat,7,0,2507
3650,2024-12-29,20241229,2024,Q4-2024,8100,Q4,December 2024,Dec 2024,24300,December,Dec,12,Sunday,Sun,1,0,2507
3651,2024-12-30,20241230,2024,Q4-2024,8100,Q4,December 2024,Dec 2024,24300,December,Dec,12,Monday,Mon,2,1,2508
3652,2024-12-31,20241231,2024,Q4-2024,8100,Q4,December 2024,Dec 2024,24300,December,Dec,12,Tuesday,Tue,3,1,2509

## Net Revenue

In [15]:
%%sql

SELECT *,
   quantity * netprice * exchangerate as netrevenue
FROM sales
LIMIT 5;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate,netrevenue
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64,63.49
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64,423.28
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00,108.75
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00,1146.75
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00,950.25

## Sales >= 202

In [16]:
%%sql

SELECT
    orderdate,
    quantity * netprice  * exchangerate AS net_revenue
FROM sales
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2015-01-01        63.49
1  2015-01-01       423.28
2  2015-01-01       108.75
3  2015-01-01      1146.75
4  2015-01-01       950.25
5  2015-01-01      1302.91
6  2015-01-01        58.73
7  2015-01-01       224.98
8  2015-01-01       263.11
9  2015-01-01       578.52

## Add customer Info

In [20]:
%%sql
-- left join
SELECT
     s.orderdate,
     s.quantity * s.netprice * s.exchangerate AS net_revenue,
     c.givenname,
     c.surname,
     c.countryfull,
     c.continent
FROM
     sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE
      orderdate::date >= '2020-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue givenname surname    countryfull      continent
0  2020-01-01        99.47     Heike  Burger        Germany         Europe
1  2020-01-01       139.97     Heike  Burger        Germany         Europe
2  2020-01-01       669.39     Heike  Burger        Germany         Europe
3  2020-01-01      4090.60     Heike  Burger        Germany         Europe
4  2020-01-01       237.15  Michelle  Seeber         Canada  North America
5  2020-01-01      1507.16     Jason   Smith  United States  North America
6  2020-01-01       189.35     Jason   Smith  United States  North America
7  2020-01-01       539.90     Jason   Smith  United States  North America
8  2020-01-01      5590.00     James    Frye  United States  North America
9  2020-01-01      3580.00    Johnny   Couch  United States  North America

In [24]:
%%sql
SELECT
        s.orderdate,
        s.quantity * s.netprice * s.exchangerate AS net_revenue,
        c.givenname,
        c.surname,
        c.countryfull,
        c.continent,
        p.productname,
        p.categoryname
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
        orderdate::date >= '2020-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productname,categoryname
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,MGS Bicycle Card Games2009 E166,Games and Toys
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,MGS Bicycle Board Games2009 E165,Games and Toys
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,Proseware Wireless Photo All-in-One Printer M3...,Computers
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,Adventure Works Laptop12 M1200 Black,Computers
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders
5,2020-01-01,1507.16,Jason,Smith,United States,North America,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances
6,2020-01-01,189.35,Jason,Smith,United States,North America,MGS Flight Simulator X M250,Games and Toys
7,2020-01-01,539.90,Jason,Smith,United States,North America,Adventure Works Desktop PC1.60 ED160 White,Computers
8,2020-01-01,5590.00,James,Frye,United States,North America,WWI Desktop PC2.30 M2300 Silver,Computers
9,2020-01-01,3580.00,Johnny,Couch,United States,North America,WWI LCD19W M100 White,Computers

In [ ]:
%%sql
SELECT
        s.orderdate,
        s.quantity * s.netprice * s.exchangerate AS net_revenue,
        c.givenname,
        c.surname,
        c.countryfull,
        c.continent,
        p.productname,
        p.categoryname,
        p.subcategoryname
CASE WHEN s.quantity * s.netprice * s.exchangerate AS net_revenue
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
        orderdate::date >= '2020-01-01'
LIMIT 10