<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/Data_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install the psycopg2 library to connect to PostgreSQL
%pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 65.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [2]:
import pandas as pd
import sqlalchemy as sa
import psycopg2
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:

# Load SQL extension
%load_ext sql

# Connect to the database
%sql postgresql://postgres:5432@localhost:5432/contoso_100k

# Enable auto pandas conversion
%config SqlMagic.autopandas = True

# Disable named parameters
%config SqlMagic.named_parameters = "disabled"

# Display numbers to 2 decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [11]:
%%sql
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2              date
3           product
4             sales
5             store

In [12]:
%%sql

SELECT table_name
FROM information_schema.tables

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

209 rows affected.

               table_name
0        currencyexchange
1                customer
2                   sales
3                    date
4                 product
..                    ...
204       foreign_servers
205    _pg_foreign_tables
206  user_mapping_options
207        foreign_tables
208     _pg_user_mappings

[209 rows x 1 columns]

In [ ]:
%%sql

SELECT *
FROM information_schema