<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/DATE%26TIME.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:

if 'google.colab' in sys.modules:
    !sudo apt-get update -qq > /dev/null 2>&1
    !sudo apt-get install postgresql -qq > /dev/null 2>&1
    !sudo service postgresql start > /dev/null 2>&1
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '5432';" > /dev/null 2>&1
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

%reload_ext sql
%sql postgresql://postgres:5432@localhost:5432/contoso_100k
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = 0
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

## Date Trunc

In [3]:
%%sql

SELECT
     orderdate
FROM sales
LIMIT 10;

    orderdate
0  2015-01-01
1  2015-01-01
2  2015-01-01
3  2015-01-01
4  2015-01-01
5  2015-01-01
6  2015-01-01
7  2015-01-01
8  2015-01-01
9  2015-01-01

In [5]:
%%sql


SELECT
        orderdate,
        DATE_TRUNC('month', orderdate):: date AS order_month
FROM sales
ORDER BY random()
LIMIT 10;

    orderdate order_month
0  2019-05-10  2019-05-01
1  2019-06-14  2019-06-01
2  2024-03-07  2024-03-01
3  2016-09-28  2016-09-01
4  2023-05-27  2023-05-01
5  2023-09-21  2023-09-01
6  2023-12-07  2023-12-01
7  2018-11-16  2018-11-01
8  2023-08-16  2023-08-01
9  2023-06-17  2023-06-01

In [6]:
%%sql


SELECT
        orderdate,
        DATE_TRUNC('month', orderdate):: date AS order_month,
        DATE_TRUNC('quarter', orderdate):: date AS order_quarter,
        DATE_TRUNC('year', orderdate):: date AS order_year
FROM sales
ORDER BY random()
LIMIT 10;

    orderdate order_month order_quarter  order_year
0  2024-02-22  2024-02-01    2024-01-01  2024-01-01
1  2017-08-19  2017-08-01    2017-07-01  2017-01-01
2  2023-10-28  2023-10-01    2023-10-01  2023-01-01
3  2017-12-19  2017-12-01    2017-10-01  2017-01-01
4  2021-12-15  2021-12-01    2021-10-01  2021-01-01
5  2019-07-09  2019-07-01    2019-07-01  2019-01-01
6  2017-02-02  2017-02-01    2017-01-01  2017-01-01
7  2022-05-05  2022-05-01    2022-04-01  2022-01-01
8  2022-02-12  2022-02-01    2022-01-01  2022-01-01
9  2019-02-22  2019-02-01    2019-01-01  2019-01-01