<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/DATE%26TIME.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:

if 'google.colab' in sys.modules:
    !sudo apt-get update -qq > /dev/null 2>&1
    !sudo apt-get install postgresql -qq > /dev/null 2>&1
    !sudo service postgresql start > /dev/null 2>&1
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '5432';" > /dev/null 2>&1
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

%reload_ext sql
%sql postgresql://postgres:5432@localhost:5432/contoso_100k
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = 0
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

## Date Trunc

In [3]:
%%sql

SELECT
     orderdate
FROM sales
LIMIT 10;

    orderdate
0  2015-01-01
1  2015-01-01
2  2015-01-01
3  2015-01-01
4  2015-01-01
5  2015-01-01
6  2015-01-01
7  2015-01-01
8  2015-01-01
9  2015-01-01

In [5]:
%%sql


SELECT
        orderdate,
        DATE_TRUNC('month', orderdate):: date AS order_month
FROM sales
ORDER BY random()
LIMIT 10;

    orderdate order_month
0  2019-05-10  2019-05-01
1  2019-06-14  2019-06-01
2  2024-03-07  2024-03-01
3  2016-09-28  2016-09-01
4  2023-05-27  2023-05-01
5  2023-09-21  2023-09-01
6  2023-12-07  2023-12-01
7  2018-11-16  2018-11-01
8  2023-08-16  2023-08-01
9  2023-06-17  2023-06-01

In [6]:
%%sql


SELECT
        orderdate,
        DATE_TRUNC('month', orderdate):: date AS order_month,
        DATE_TRUNC('quarter', orderdate):: date AS order_quarter,
        DATE_TRUNC('year', orderdate):: date AS order_year
FROM sales
ORDER BY random()
LIMIT 10;

    orderdate order_month order_quarter  order_year
0  2024-02-22  2024-02-01    2024-01-01  2024-01-01
1  2017-08-19  2017-08-01    2017-07-01  2017-01-01
2  2023-10-28  2023-10-01    2023-10-01  2023-01-01
3  2017-12-19  2017-12-01    2017-10-01  2017-01-01
4  2021-12-15  2021-12-01    2021-10-01  2021-01-01
5  2019-07-09  2019-07-01    2019-07-01  2019-01-01
6  2017-02-02  2017-02-01    2017-01-01  2017-01-01
7  2022-05-05  2022-05-01    2022-04-01  2022-01-01
8  2022-02-12  2022-02-01    2022-01-01  2022-01-01
9  2019-02-22  2019-02-01    2019-01-01  2019-01-01

In [10]:
%%sql


SELECT
        DATE_TRUNC('month', orderdate):: date AS order_month,
        SUM(quantity * netprice * exchangerate) AS net_revenue,
        COUNT(DISTINCT customerkey) AS customers_id
FROM sales
GROUP BY
         order_month
LIMIT 10;

  order_month  net_revenue  customers_id
0  2015-01-01    384092.66           200
1  2015-02-01    706374.12           291
2  2015-03-01    332961.59           139
3  2015-04-01    160767.00            78
4  2015-05-01    548632.63           236
5  2015-06-01    748563.97           238
6  2015-07-01    635376.13           227
7  2015-08-01    718538.62           235
8  2015-09-01    696805.68           277
9  2015-10-01    824891.22           304

In [11]:
%%sql


SELECT
         TO_CHAR(orderdate, 'YYYY-MM') AS order_month,
         SUM(quantity * netprice * exchangerate) AS net_revenue,
         COUNT(DISTINCT customerkey) AS customers_total
FROM sales
GROUP BY
            order_month
LIMIT 10;

  order_month  net_revenue  customers_total
0     2015-01    384092.66              200
1     2015-02    706374.12              291
2     2015-03    332961.59              139
3     2015-04    160767.00               78
4     2015-05    548632.63              236
5     2015-06    748563.97              238
6     2015-07    635376.13              227
7     2015-08    718538.62              235
8     2015-09    696805.68              277
9     2015-10    824891.22              304

In [12]:
%%sql

SELECT
       orderdate,
       DATE_PART('month', orderdate) AS order_month,
       DATE_PART('year', orderdate) AS order_year,
       DATE_PART('day', orderdate) AS order_day
FROM sales
LIMIT 10;

    orderdate  order_month  order_year  order_day
0  2015-01-01         1.00     2015.00       1.00
1  2015-01-01         1.00     2015.00       1.00
2  2015-01-01         1.00     2015.00       1.00
3  2015-01-01         1.00     2015.00       1.00
4  2015-01-01         1.00     2015.00       1.00
5  2015-01-01         1.00     2015.00       1.00
6  2015-01-01         1.00     2015.00       1.00
7  2015-01-01         1.00     2015.00       1.00
8  2015-01-01         1.00     2015.00       1.00
9  2015-01-01         1.00     2015.00       1.00

In [16]:
%%sql

SELECT
    orderdate,
    EXTRACT(month FROM orderdate) AS order_month,
    EXTRACT(year  FROM orderdate) AS order_year,
    EXTRACT(day   FROM orderdate) AS order_day
FROM sales

         orderdate order_month order_year order_day
0       2015-01-01           1       2015         1
1       2015-01-01           1       2015         1
2       2015-01-01           1       2015         1
3       2015-01-01           1       2015         1
4       2015-01-01           1       2015         1
...            ...         ...        ...       ...
199868  2024-04-20           4       2024        20
199869  2024-04-20           4       2024        20
199870  2024-04-20           4       2024        20
199871  2024-04-20           4       2024        20
199872  2024-04-20           4       2024        20

[199873 rows x 4 columns]

In [17]:
%%sql

SELECT CURRENT_DATE

  current_date
0   2026-06-05

In [19]:
%%sql

SELECT NOW()

                               now
0 2026-06-05 13:29:06.963030+00:00

In [22]:
%%sql
SELECT
    CURRENT_DATE,
    EXTRACT(year FROM orderdate) AS order_year,
    EXTRACT(year FROM CURRENT_DATE) AS current_year,
    s.orderdate,
    p.categoryname,
    SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
    s.orderdate,
    p.categoryname
ORDER BY
    s.orderdate,
    p.categoryname;

,current_date,order_year,current_year,orderdate,categoryname,net_revenue
0,2026-06-05,2015,2026,2015-01-01,Audio,1555.67
1,2026-06-05,2015,2026,2015-01-01,Cameras and camcorders,4977.13
2,2026-06-05,2015,2026,2015-01-01,Computers,3066.35
3,2026-06-05,2015,2026,2015-01-01,Games and Toys,163.87
4,2026-06-05,2015,2026,2015-01-01,Home Appliances,1152.57
...,...,...,...,...,...,...
23491,2026-06-05,2024,2026,2024-04-20,Computers,58353.68
23492,2026-06-05,2024,2026,2024-04-20,Games and Toys,1744.30
23493,2026-06-05,2024,2026,2024-04-20,Home Appliances,1562.04
23494,2026-06-05,2024,2026,2024-04-20,"Music, Movies and Audio Books",4949.43
23495,2026-06-05,2024,2026,2024-04-20,TV and Video,9841.91