<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/window_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import sqlalchemy as sa
import psycopg2
import sys
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:


if 'google.colab' in sys.modules:
    !sudo apt-get update -qq > /dev/null 2>&1
    !sudo apt-get install postgresql -qq > /dev/null 2>&1
    !sudo service postgresql start > /dev/null 2>&1
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '5432';" > /dev/null 2>&1
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

%reload_ext sql
%sql postgresql://postgres:5432@localhost:5432/contoso_100k
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = 0
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

### Windows functions

*Perform calculations across a set of tables rows related to the current row.*
*Dont group the results into a single output row.*

*Over()* Defines the window for the function.

*Partition BY : Divides the result into partions. The function is then applied to each paertition.*

In [7]:
%%sql


SELECT
         customerkey,
         orderkey,
         linenumber,
         (quantity * netprice * exchangerate) AS net_revenue,
         AVG (quantity * netprice * exchangerate)  OVER() AS avg_net_revenue_all_orders,
         AVG (quantity * netprice * exchangerate)  OVER(PARTITION BY customerkey) AS avg_net_revenue_per_customer
FROM sales
ORDER BY
          customerkey
LIMIT 10

,customerkey,orderkey,linenumber,net_revenue,avg_net_revenue_all_orders,avg_net_revenue_per_customer
0,15,2259001,0,2217.41,1032.69,2217.41
1,180,1305016,0,525.31,1032.69,836.74
2,180,3162018,1,1913.55,1032.69,836.74
3,180,3162018,0,71.36,1032.69,836.74
4,185,1613010,0,1395.52,1032.69,1395.52
5,243,505008,0,287.67,1032.69,287.67
6,387,2495044,0,1265.56,1032.69,517.32
7,387,1451007,3,45.62,1032.69,517.32
8,387,1451007,2,97.05,1032.69,517.32
9,387,1451007,0,1608.10,1032.69,517.32

In [8]:
%%sql


SELECT
         customerkey AS customer,
         orderdate,
         (quantity * netprice * exchangerate) AS net_revenue,
         SUM (quantity * netprice * exchangerate)  OVER(PARTITION BY customerkey ORDER BY orderdate) AS cum_net_revenue_per_customer
FROM sales
ORDER BY
          customerkey

        customer   orderdate  net_revenue  cum_net_revenue_per_customer
0             15  2021-03-08      2217.41                       2217.41
1            180  2018-07-28       525.31                        525.31
2            180  2023-08-28        71.36                       2510.22
3            180  2023-08-28      1913.55                       2510.22
4            185  2019-06-01      1395.52                       1395.52
...          ...         ...          ...                           ...
199868   2099711  2016-08-13      2067.75                       2067.75
199869   2099711  2017-08-14      3940.92                       6008.67
199870   2099743  2022-03-17       375.57                        469.62
199871   2099743  2022-03-17        94.05                        469.62
199872   2099743  2023-02-11       598.46                       1068.08

[199873 rows x 4 columns]

In [12]:
%%sql


SELECT
          customerkey AS customer,
          orderdate,
          (quantity * netprice * exchangerate) AS net_revenue,
          ROW_NUMBER() OVER(
                            PARTITION BY customerkey
                            ORDER BY quantity * netprice * exchangerate DESC
                            ) AS order_rank,
          SUM (quantity * netprice * exchangerate)  OVER(PARTITION BY customerkey ORDER BY orderdate) AS customer_running_total,
          ((quantity * netprice * exchangerate) / SUM (quantity * netprice * exchangerate) OVER(PARTITION BY customerkey) *100 ) AS pct_of_total_revenue
FROM sales
ORDER BY
          customerkey, orderdate
LIMIT 10

,customer,orderdate,net_revenue,order_rank,customer_running_total,pct_of_total_revenue
0,15,2021-03-08,2217.41,1,2217.41,100.00
1,180,2018-07-28,525.31,2,525.31,20.93
2,180,2023-08-28,1913.55,1,2510.22,76.23
3,180,2023-08-28,71.36,3,2510.22,2.84
4,185,2019-06-01,1395.52,1,1395.52,100.00
5,243,2016-05-19,287.67,1,287.67,100.00
6,387,2018-12-21,619.77,3,2370.54,13.31
7,387,2018-12-21,1608.10,1,2370.54,34.54
8,387,2018-12-21,97.05,7,2370.54,2.08
9,387,2018-12-21,45.62,8,2370.54,0.98

In [13]:
%%sql

SELECT
      orderdate,
      orderkey,
      linenumber,
      orderkey *10 + linenumber AS order_line_number,
      (quantity * netprice * exchangerate) AS net_revenue
FROM sales
ORDER BY order_line_number
LIMIT 10

    orderdate  orderkey  linenumber  order_line_number  net_revenue
0  2015-01-01      1000           0              10000        63.49
1  2015-01-01      1000           1              10001       423.28
2  2015-01-01      1001           0              10010       108.75
3  2015-01-01      1002           0              10020      1146.75
4  2015-01-01      1002           1              10021       950.25
5  2015-01-01      1002           2              10022      1302.91
6  2015-01-01      1002           3              10023        58.73
7  2015-01-01      1003           0              10030       224.98
8  2015-01-01      1004           0              10040       263.11
9  2015-01-01      1004           1              10041       578.52

In [15]:
%%sql

SELECT
          orderdate,
          orderkey * 10 + linenumber AS order_line_number,
          (quantity * netprice * exchangerate) AS net_revenue,
          SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS daily_net_revenue,
          ((quantity * netprice * exchangerate) / SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) *100 ) AS pct_of_daily_revenue
FROM sales
ORDER BY orderdate, pct_of_daily_revenue DESC
LIMIT 10

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_of_daily_revenue
0,2015-01-01,10043,2395.10,11640.80,20.58
1,2015-01-01,10061,1552.32,11640.80,13.34
2,2015-01-01,10022,1302.91,11640.80,11.19
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10050,975.16,11640.80,8.38
5,2015-01-01,10021,950.25,11640.80,8.16
6,2015-01-01,10041,578.52,11640.80,4.97
7,2015-01-01,10081,574.05,11640.80,4.93
8,2015-01-01,10001,423.28,11640.80,3.64
9,2015-01-01,10040,263.11,11640.80,2.26

In [21]:
%%sql

SELECT *,
      100 * net_revenue / SUM(net_revenue) OVER(PARTITION BY orderdate) AS pct_of_daily_revenue
FROM (
      SELECT
            orderdate,
            orderkey * 10 + linenumber AS order_line_number,
            (quantity * netprice * exchangerate) AS net_revenue,
            SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS daily_net_revenue
      FROM sales
      ORDER BY orderdate
      ) AS daily_sales
LIMIT 10

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_of_daily_revenue
0,2015-01-01,10000,63.49,11640.80,0.55
1,2015-01-01,10001,423.28,11640.80,3.64
2,2015-01-01,10010,108.75,11640.80,0.93
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10021,950.25,11640.80,8.16
5,2015-01-01,10022,1302.91,11640.80,11.19
6,2015-01-01,10023,58.73,11640.80,0.50
7,2015-01-01,10030,224.98,11640.80,1.93
8,2015-01-01,10040,263.11,11640.80,2.26
9,2015-01-01,10041,578.52,11640.80,4.97