<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/window_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

if 'google.colab' in sys.modules:
    !sudo apt-get update -qq > /dev/null 2>&1
    !sudo apt-get install postgresql -qq > /dev/null 2>&1
    !sudo service postgresql start > /dev/null 2>&1
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '5432';" > /dev/null 2>&1
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

%reload_ext sql
%sql postgresql://postgres:5432@localhost:5432/contoso_100k
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = 0
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

## Row_Num

*Return the number of the current view within its partition counting from 1*


- **`RANK()`** — skips numbers after a tie *(1, 2, 2, **4**, 5)*
- **`DENSE_RANK()`** — never skips, always continues sequentially *(1, 2, 2, **3**, 4)*

In [4]:
%%sql

SELECT
          customerkey,
          COUNT(*) AS total_orders,
          ROW_NUMBER() OVER(ORDER BY COUNT(*) DESC) AS row_num,
          RANK() OVER(ORDER BY COUNT(*) DESC) AS rank,
          DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) AS dense_rank
FROM sales
GROUP BY customerkey
LIMIT 10

   customerkey  total_orders  row_num  rank  dense_rank
0      1834524            31        1     1           1
1      1375597            30        2     2           2
2       249557            27        3     3           3
3       459519            26        4     4           4
4      1495941            26        5     4           4
5      1801215            26        6     4           4
6      1219056            25        7     7           5
7       759419            24        8     8           6
8      1427444            24        9     8           6
9      1876222            24       10     8           6

* FIRST_VALUE() — fetches the value from the first row of the window *
* LAST_VALUE() — fetches the value from the last row of the window *
* NTH_VALUE() — fetches the value from the nth row of the window *

In [7]:
%%sql

SELECT
        TO_CHAR(orderdate, 'YYYY-MM') AS year_month,
        SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = '2020'
GROUP BY year_month
ORDER BY year_month
LIMIT 10

  year_month  net_revenue
0    2020-01   2132132.93
1    2020-02   2713593.19
2    2020-03   1127542.88
3    2020-04    508319.95
4    2020-05   1215685.60
5    2020-06    799668.45
6    2020-07    619914.74
7    2020-08    524675.33
8    2020-09    328013.12
9    2020-10    381504.82

In [11]:
%%sql

WITH monthly_revenue AS (
SELECT
        TO_CHAR(orderdate, 'YYYY-MM') AS year_month,
        SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = '2020'
GROUP BY year_month
ORDER BY year_month
LIMIT 10
)

SELECT *,
          FIRST_VALUE(net_revenue) OVER(ORDER BY net_revenue) AS first_month_revenue,
          LAST_VALUE(net_revenue) OVER(ORDER BY net_revenue) AS last_month_revenue,
          NTH_VALUE(net_revenue, 3) OVER(ORDER BY net_revenue) AS third_month_revenue
FROM
          monthly_revenue

,year_month,net_revenue,first_month_revenue,last_month_revenue,third_month_revenue
0,2020-09,328013.12,328013.12,328013.12,NaN
1,2020-10,381504.82,328013.12,381504.82,NaN
2,2020-04,508319.95,328013.12,508319.95,508319.95
3,2020-08,524675.33,328013.12,524675.33,508319.95
4,2020-07,619914.74,328013.12,619914.74,508319.95
5,2020-06,799668.45,328013.12,799668.45,508319.95
6,2020-03,1127542.88,328013.12,1127542.88,508319.95
7,2020-05,1215685.60,328013.12,1215685.60,508319.95
8,2020-01,2132132.93,328013.12,2132132.93,508319.95
9,2020-02,2713593.19,328013.12,2713593.19,508319.95